universe                = docker
docker_image            = pytorch/pytorch:latest
executable              = run_task3_sweep.sh
arguments               = z7avvqti
transfer_input_files    = task3.py, requirements.txt, task1_best_model.pt, External-Dataset_for_Task2.csv
transfer_output_files   = logs/, saved_models/
transfer_output_remaps  = "logs=results/task3/sweep/logs, saved_models=results/task3/sweep/saved_models"
output                  = results/task3/sweep/logs/task3.$(ClusterId).$(ProcId).out
error                   = results/task3/sweep/logs/task3.$(ClusterId).$(ProcId).err
log                     = results/task3/sweep/logs/task3.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs            = 1
request_CPUs            = 4
request_memory          = 16G
requirements            = UidDomain == "cs.uni-saarland.de"
getenv                  = HOME
+WantGPUHomeMounted     = true
environment             = "WANDB_API_KEY=REDACTED_WANDB_API_KEY;WANDB_ENTITY=mobashirrahman-saarland-university;ANDB_PROJECT=Task3;WANDB_SWEEP=true"
queue 1
