universe                = docker
docker_image            = pytorch/pytorch:latest
executable              = run_task2.sh
transfer_input_files    = task2.py, requirements.txt, External-Dataset_for_Task2.csv, task1_best_model.pt
transfer_output_files   = logs/, saved_models/
transfer_output_remaps  = "logs=results/task2/logs, saved_models=results/task2/saved_models"
output                  = results/task2/logs/task2.$(ClusterId).$(ProcId).out
error                   = results/task2/logs/task2.$(ClusterId).$(ProcId).err
log                     = results/task2/logs/task2.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs            = 1
request_CPUs            = 4
request_memory          = 16G
requirements            = UidDomain == "cs.uni-saarland.de"
getenv                  = HOME
+WantGPUHomeMounted     = true
environment             = "WANDB_API_KEY=REDACTED_WANDB_API_KEY;WANDB_ENTITY=mobashirrahman-saarland-university;ANDB_PROJECT=Task2_InfluenceFunctions;WANDB_SWEEP=true"
queue 1
